---
- hosts: all
  become: true
  tasks:
    - name: create folder
      file:
        path: /{{item}}
        state: directory
        mode: '0755'
      loop:
        - vote
        - worker
        - result
    - name: copy folder
      copy:
        src: TP_Docker/{{item}}/
        dest: /{{item}}/
      loop:
        - vote
        - result
        - worker 
    - name: build image
      command: docker build -t {{item}} /{{item}}/.
      loop:
        - vote
        - result
        - worker