---
- hosts: all
  become: true
  tasks:
  - name: update distribution
    apt:
      update_cache: yes
  - name: install apache2
    apt:
      name:
        - apache2
  - name: droits ecriture
    command: chmod -R 0777 /var/www/html/;
  - name: file html copy
    copy: 
      src: trucshtml/
      dest: /var/www/html/
  - name: start apache2
    command: systemctl start apache2