---
- hosts: all
  become: true
  tasks:
    - name: update distibution debian
      apt:
        update_cache: yes
      when: ansible_facts['os_family'] == 'Debian'
    - name: update distibution centos
      shell: yum install -y yum-utils
      when: ansible_facts['os_family'] == 'RedHat'
    - name: install prerequisite debian
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg2
          - lsb-release
      when: ansible_facts['os_family'] == 'Debian'
    - name: install prerequisite centos
      shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
      when: ansible_facts['os_family'] == 'RedHat'
    - name: ajout cle gpg
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
      when: ansible_facts['os_family'] == 'Debian'
    - name: adresse repo
      apt_repository:
        repo: deb https://download.docker.com/linux/debian bionic stable
      when: ansible_facts['os_family'] == 'Debian'
    - name: update distibution
      apt:
        update_cache: yes
      when: ansible_facts['os_family'] == 'Debian'
    - name: install docker-ce
      apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
      when: ansible_facts['os_family'] == 'Debian'
    - name: install docker centos
      shell: yum install docker-ce docker-ce-cli containerd.io
      when: ansible_facts['os_family'] == 'RedHat'
    - name: delete directory
      file:
        path: /TP_Docker
        state: absent
    - name: copy repo TP
      copy: 
        src: TP_Docker/
        dest: /TP_Docker/
  # démarrage du service
    - name: start docker service
      service:
        name: docker start
        state: started
        enabled: true
    # - name: docker build worker
    #   shell: docker build -t worker-app /TP_Docker/worker/  
    # - name: docker build vote
    #   shell: docker build -t vote-app /TP_Docker/vote/     
    # - name: docker build result
    #   shell: docker build -t result-app /TP_Docker/result/     