---
- hosts: all
  become: true
  tasks:
    - name: update distibution
      apt:
        update_cache: yes
    - name: install docker
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg2
          - software-properties-common
    - name: truc curl chelou
      shell: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
    - name: truc repo chelou
      shell: add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
    - name: update distibution
      apt:
        update_cache: yes
    - name: policy docker-ce
      shell: apt-cache policy docker-ce
    - name: delete directory
      file:
        path: /TP_Docker
        state: absent
    - name: copy repo TP
      copy: 
        src: TP_Docker/
        dest: /TP_Docker/
    # - name: start docker
    - name: image worker
      docker_image:
        name: worker-app
        buildargs: 
          path: /TP_Docker/worker
          source: build
        state: present
    - name: image vote
      docker_image:
        name: vote-app
        buildargs: 
          path: /TP_Docker/vote
          source: build
        state: present
    - name: image result
      docker_image:
        name: result-app
        buildargs: 
          path: /TP_Docker/result
          source: build
        state: present
    - name: delete directory
      file:
        path: /TP_Docker
        state: absent