---
- hosts: all
  become: true
  tasks:
  # - name: update distribution
  #   apt:
  #     update_cache: yes
  # - name: install apache2
  #   apt:
  #     name:
  #       - apache2
  - name: droits ecriture
    ansible.builtin.file: 
      path: /var/www/html
      mode: '0777'
      recurse: yes
  - name: file html copy
    copy: 
      src: trucshtml/
      dest: /var/www/html/
  - name: start apache2
    command: systemctl start apache2