---
- hosts: all
  become: true
  tasks:
    - name: update distibution
      apt:
        update_cache: yes
    - name: install prerequisite docker
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg2
          - lsb-release
    - name: ajout cle gpg
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
    - name: adresse repo
      apt_repository:
        repo: deb https://download.docker.com/linux/debian bionic stable
    - name: update distibution
      apt:
        update_cache: yes
    - name: install docker-ce
      apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
    - name: delete directory
      file:
        path: /TP_Docker
        state: absent
    - name: copy repo TP
      copy: 
        src: TP_Docker/
        dest: /TP_Docker/
  # démarrage du service
    - name: start docker service
      service:
        name: docker start
        state: started
        enabled: true
    # - name: docker build worker
    #   shell: docker build -t worker-app /TP_Docker/worker/  
    # - name: docker build vote
    #   shell: docker build -t vote-app /TP_Docker/vote/     
    # - name: docker build result
    #   shell: docker build -t result-app /TP_Docker/result/     