---
- hosts: all
  become: true
  tasks:
  # - name: droits ecriture
  #   ansible.builtin.file: 
  #   - path: /var/www/html
  #     state: directory
  #     mode: '0777'
  #     owner: root
  #     group: root
  #     recurse: yes
  - name: file html copy
    copy: 
      src: trucshtml/
      dest: /var/www/html/
  - name: start apache2
    command: systemctl restart apache2